# Generated by Django 5.2.4 on 2025-07-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_filial_location_filial'),
        ('superadmin', '0002_filial_remove_administrator_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
