# Generated by Django 5.2.4 on 2025-07-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_delete_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='filia_name',
            new_name='filial_name',
        ),
    ]
