# Generated by Django 5.2.4 on 2025-07-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location'),
        ('superadmin', '0002_filial_remove_administrator_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.filial'),
        ),
        migrations.AddField(
            model_name='location',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.filial'),
        ),
    ]
