# Generated by Django 5.2.4 on 2025-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_filial_location_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_check',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
