# Generated by Django 4.2.3 on 2025-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendance_check_in_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
