# Generated by Django 4.2.3 on 2025-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_attendance_check_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_check',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='check_in_check',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
