# Generated by Django 4.2.3 on 2025-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_attendance_check_in_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='check_in_check',
        ),
        migrations.AddField(
            model_name='employee',
            name='check_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
