# Generated by Django 5.2.4 on 2025-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_employee_check_in_check_employee_check_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='check_number',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
