# Generated by Django 5.2.4 on 2025-10-12 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_employee_image'),
        ('superadmin', '0005_organization_administrator_is_org_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.organization'),
        ),
    ]
